# Generated by Django 3.2.8 on 2021-10-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcollection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardcollection',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
