# Generated by Django 3.2.8 on 2021-10-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20211014_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='cardcollection',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='cardtopic',
            name='external_id',
        ),
    ]
